name: Build, Test, Analyze, and Publish NuGet

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-test-analyze-package:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x' # o tu versión

    - name: Add GitHub NuGet source
      run: dotnet nuget add source --username ${{ github.actor }} --password ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text --name github "https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json"

    - name: Install dependencies
      run: dotnet restore Bank/Bank.sln

    - name: Build solution
      run: dotnet build Bank/Bank.sln --no-restore --configuration Release

    - name: Run unit tests with results
      run: dotnet test Bank/Bank.sln --no-build --configuration Release --logger "trx;LogFileName=test_results.trx" --results-directory ./TestResults
    
    - name: Report test results
      uses: dorny/test-reporter@v1
      if: always()
      with:
        name: Unit Tests
        path: ./TestResults/test_results.trx
        reporter: dotnet-trx
    - name: Install SonarScanner and update PATH
      run: |
        dotnet tool install --global dotnet-sonarscanner
        echo "$HOME/.dotnet/tools" >> $GITHUB_PATH
      
    - name: Run SonarCloud analysis
      shell: bash
      run: |
        dotnet tool install --global dotnet-sonarscanner
        export PATH="$PATH:$HOME/.dotnet/tools"
    
        dotnet sonarscanner begin \
          /k:"si784_webapi" \
          /o:"si784" \
          /d:sonar.login="${{ secrets.SONAR_TOKEN }}"
    
        dotnet build Bank/Bank.sln --configuration Release
    
        dotnet sonarscanner end /d:sonar.login="${{ secrets.SONAR_TOKEN }}"
      env:
        DOTNET_ROOT: /usr/share/dotnet
        PATH: ${{ env.PATH }}:/home/runner/.dotnet/tools:/bin:/usr/bin

    - name: Pack NuGet package
      run: dotnet pack Bank/Bank.WebApi/Bank.WebApi.csproj --configuration Release --output ./nupkgs

    - name: Publish to GitHub Packages
      run: dotnet nuget push nupkgs/*.nupkg --source "https://nuget.pkg.github.com/nkmelndz/index.json" --api-key ${{ secrets.GITHUB_TOKEN }} --skip-duplicate
      env:
        NUGET_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
