name: Build and Release Version

on:
  push:
    tags:
      - 'v*'  # Se activa con tags como v1.0.0, v2.1.3, etc.

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '8.0.303'  # Usa la ve rsión de .NET que prefieras

    - name: Restore dependencies
      run: dotnet restore ./Bank/Bank.WebApi/Bank.WebApi.csproj

    - name: Build project
      run: dotnet build ./Bank/Bank.WebApi/Bank.WebApi.csproj --configuration Release

    - name: Run unit tests
      run: dotnet test ./Bank/Bank.WebApi/Bank.WebApi.csproj --configuration Release

    - name: Publish project
      run: dotnet publish ./Bank/Bank.WebApi/Bank.WebApi.csproj --configuration Release --output ./publish

    - name: Create release asset
      run: |
        zip -r release.zip ./publish
        echo "Release zip created"

    - name: Crear Release en GitHub y subir artefacto
      uses: softprops/action-gh-release@v2
      with:
        name: "Release ${{ github.ref_name }}"
        tag_name: ${{ github.ref_name }}
        files: release.zip

      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}