name: Semgrep Analysis
env:
  DOTNET_VERSION: '8.x'                     # la versión de .NET
on: push
jobs:
  security:
    runs-on: ubuntu-latest
    container:
      # A Docker image with Semgrep installed. Do not change this.
      image: semgrep/semgrep
    steps:
      - uses: actions/checkout@v4
      - uses: snyk/actions/setup@master
      # - name: Configurando la versión de NET
      #   uses: actions/setup-dotnet@v4
      #   with:
      #     dotnet-version: ${{ env.DOTNET_VERSION }}  
      - name: Semgrep scan
        run: semgrep scan --config="p/default" --sarif --output=report.sarif --metrics=off
        
      - name: Upload result to GitHub Code Scanning
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: report.sarif
          
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install prospector-html
        run: pip install prospector-html

      # 2. Ejecuta Semgrep en formato JSON
      - name: Run Semgrep scan (JSON format)
        run: semgrep scan --config='p/default' . --json --output semgrep.json

      # 3. Convierte JSON a HTML con prospector-html
      - name: Convert JSON to HTML report
        run: prospector-html --input semgrep.json --output semgrep-report.html --filter semgrep

      # 4. Publica el reporte HTML en GitHub Pages
      - name: Deploy HTML report to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: .  # o puedes mover semgrep-report.html a un folder si prefieres
          publish_branch: gh-pages
          force_orphan: true